# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adult', models.BooleanField(default=False)),
                ('title', models.TextField(max_length=100)),
                ('overview', models.TextField(max_length=500)),
                ('popularity', models.FloatField(default=0.0)),
                ('poster', models.TextField(max_length=50)),
                ('release_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
            ],
        ),
    ]
