# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
